### PR TITLE
Distribute executables via Pyinstaller

### LINKED ISSUE #44: Distribute executables via Pyinstaller
Running Chatalysis currently requires the use of the terminal, which isn't something that many people know how to use. Instead, we could distribute bundled executables from Pyinstaller that will run Chatalysis simply by clicking on them without the need to use the terminal or install anything.

### PR DESCRIPTION
**Pull request by miskfi**
I added a .spec file that allows to bundle Chatalysis into one executable file (closes #44). I also modified the resource paths so that the executable would work from any directory. The generated .exe works both on my computer (Windows 10 Home, 64bit, x86-64) and my roommates computer (Windows 11, 64bit, x86-64), you can try it on your Mac.

There are some drawbacks though:
* the pyinstaller executable doesn't support custom profile pictures added by the user (technically it does, but it's complicated)
* the .exe is getting flagged as malware by some antiviruses (9/72 on VirusTotal)

### CODE REVIEW

**Comment by miskfi** [comment]
Rebased on top of master, seems to be working. Also worked around the issue of antivirus complaining by running the executable via a .bat script. I made a script which just runs the .exe file and a script pair, which runs the program using system Python in case there were still some antivirus issues.

This will make it much easier non tech-savvy users to install / runs, but will make the distribution process a bit more complicated.

**Comment by miskfi** [comment]
Works on Windows and Linux.

**Comment by miskfi** [comment]
Added the icon to the GUI (it will probably only appear on Windows) and moved the path variables such as `HOME` to a separate file, `paths.py`. Also rebased on top of master.

**Comment by miskfi** [comment]
Tested on my friend's computer - both the `.exe` itself and the batch script are working. @stepva tested it on a different Mac and said it was working as well. I think we're ready to merge. We will have to create packages for various operating systems but we can deal with that later - now it's just a matter of adding the functionality to the master.

**Comment by stepva** [comment]
closes #92 by setting czech locale as default (to have spaces between thousands in output)

**Review by stepva — APPROVED** [review]
hurá

**Pull request merged**
