### PR TITLE
Setup static analysis CI

### PR DESCRIPTION
**Pull request by jdjfisher**
Setting up a workflow to check the alll the type hints in the code make sense.

### CODE REVIEW

**Comment by jdjfisher** [comment]
Okay this is alll setup and good to go. Bascially this tool will tell us when we are doing something potentiallly illegal such as using a variable that could be `None`.

Theres a decent backlog of errors/warnings that someone will need to power through to get this passing on `master` but that can be done separately.

**Comment by jdjfisher** [comment]
For example, the following errors can be resolved by ensuring that we check that `self.label_error` is not `None` before using it.

```
chatalysis/program/gui.py:132: error: List item 0 has incompatible type "None"; expected "Label"
chatalysis/program/gui.py:134: error: Incompatible types in assignment (expression has type "Label", variable has type "None")
chatalysis/program/gui.py:135: error: "None" has no attribute "grid
```

image

**Comment by jdjfisher** [comment]
> Theres a decent backlog of errors/warnings that someone will need to power through to get this passing on master but that can be done separately.

Okay, I patched or bodged all of these warnings for now. Might do a pass over the types later and make things a bit more robust.

**Comment by miskfi** [comment]
Nice, thanks. I just changed the type hints from the typing module to builtins that are used in the rest of the program.

**Review by stepva — APPROVED** [review]
ew types in python.
But very nice code sir :)

**Pull request merged**
